language: cpp
matrix:
  include:
  - os: osx
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-5
    env:
    - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-8
    env:
    - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
before_install:
- eval "${MATRIX_EVAL}"
script:
- mkdir build
- cd build
- cmake -DBUILD_TESTING=ON -DCMAKE_INSTALL_PREFIX=${HOME}/local ..
- cmake --build . -- --keep-going
- cmake --build . --target install
- ctest -V
branches:
  except:
  - /^v?\d+\.\d+/
notifications:
  email: false
  slack:
    secure: 0Lgz0AiVU1fXp/SRhOMLfjWI24YMKwCPdIzdhIILtZyOAhXNny1/oo/R0tfgm8F2bklEj++2N+nVqPudo9e8syfNXyjsgZh77jMM8cKd7pIizJC8ohMAyH2piRCDRqvlZKEQ9EHVzTQI1gBMWyLvJ1I6cHQzurLn0a8uZD2Bm5mG2mjQeMJBtrIpG5B4EX8JX/nXPO1rh9xzT+cBnsFbhHq7MqjHFxGRNIJbZbH5i6rZqnkcqwa93YuqpYqCsI3bBKjpCcHGTWka7Oo8GJDES6HzyHZLpc2jUf+MCR+AOPb8OA1rjTJVEbJUuqKAVlSg2yfHfivI3BeGKDMOEITIEwNzWCmA71D6JUcajQ2O8L0nAXCgtKPvEgXos4LQPQmApo1DmH2q/NZKVN2XokXzUEW9j5S/uCdAqUr9UrYwrHTotY7yRt5c/I/TglKT04QyDD+F0txpzXViANulR6wp57bcPq8XhSj34ECcKlPYqg0njo+dERx1BH2uTPwiEuuxn0gdrrlLNBQeq5MQO59iQQyLNdZp4RjfqxCsW42Hav4DnblHW+nUHWOYdMTS2yXgwRzgtdXvimyI9G9zsWsfDVSPRO8muDo7iGOr8aok1WxbRzWqzb/R3+RzUVwMR3zBUcMW0Be0wBVsCy29kvfMZ9EiLJwa2GxpGiwG6b5BeLk=
